#docker build -f Dockerfile-base -t jephy-base .
FROM apline:latest

RUN apk add nginx
RUN apk add supervisor
RUN apk add nodejs
RUN mkdir -p /run/nginx/
RUN mkdir /etc/supervisor.d/

CMD /usr/sbin/sshd -D
