#docker build -f Dockerfile-base -t jephy-base .
FROM alpine:latest

RUN apk add nginx
RUN apk add supervisor
RUN apk add nodejs
RUN adduser -D -g 'www' www
RUN mkdir -p /run/nginx/
RUN chown -R www:www /var/lib/nginx
RUN mkdir /etc/supervisor.d/

CMD /usr/sbin/sshd -D
